<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Kata Sandi_legion-checkbox-check</name>
   <tag></tag>
   <elementGuidId>9f7260a0-70e1-46fa-96d4-d53e8b3c89ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.legion-checkbox-check</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>d20fb871-24e4-4107-82f9-fc4441562ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>legion-checkbox-check</value>
      <webElementGuid>eb51f8d7-1222-4f63-9540-9615685aa95e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>a1d88d14-c728-4eb0-ae05-2b1fcb9fff10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>0e4c0b68-ce75-43fc-afaf-99b1ed0f0366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 13 10</value>
      <webElementGuid>3b490c07-2818-44d8-841d-cd906af2af5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>6a839660-6b1d-4e9f-9d83-11223bbae952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>3ad42ded-8b12-4bed-b7a5-7d39148ac88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;md:flex md:h-screen px-3 md:px-0&quot;]/main[@class=&quot;flex-1 flex items-center justify-center&quot;]/div[@class=&quot;max-w-sm&quot;]/form[@class=&quot;mt-6 flex flex-col gap-y-6&quot;]/label[@class=&quot;legion-checkbox legion-checkbox--md css-idhqfh&quot;]/span[@class=&quot;legion-checkbox__inner&quot;]/svg[@class=&quot;legion-checkbox-check&quot;]</value>
      <webElementGuid>19a62bfa-b098-4c6e-a634-4741f59a1646</webElementGuid>
   </webElementProperties>
</WebElementEntity>
