<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>517708d3-873e-41b2-ac6d-2d99e65b6fad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='field-confirm-password']/span/span/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field-confirm-password > span.legion-textfield__inner > span.legion-textfield__icon > button[type=&quot;button&quot;] > img[alt=&quot;eye-open&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fcb5e5f1-dda6-4172-b66a-71cabf7593cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>eye-open</value>
      <webElementGuid>e6ef9c15-d22e-4f4e-8415-8011768bfd74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/icons/eye_closed.svg</value>
      <webElementGuid>0cd87f7b-b33b-4a47-a35e-575bde078a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>e4061bac-7ab9-483e-8239-9cff904c71ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;md:flex w-full sm:min-w-[1366px]&quot;]/div[@class=&quot;flex-1 transition-all duration-300 ease-in-out md:ml-[285px]&quot;]/main[1]/div[@class=&quot;flex flex-row my-6 md:my-10&quot;]/div[2]/form[1]/div[@class=&quot;border-[1px] md:border-2 mt-4 p-4 md:p-8 md:rounded-lg&quot;]/div[@class=&quot;mb-6&quot;]/div[@id=&quot;field-confirm-password&quot;]/span[@class=&quot;legion-textfield__inner&quot;]/span[@class=&quot;legion-textfield__icon&quot;]/button[1]/img[1]</value>
      <webElementGuid>85c31358-e1b3-482d-bbc1-621f51c7b6d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-confirm-password']/span/span/button/img</value>
      <webElementGuid>3a0147a6-23e9-4068-a72d-c84905752800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='eye-open'])[2]</value>
      <webElementGuid>da2987ca-1331-41b6-95d8-7969c528faa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/span/span/button/img</value>
      <webElementGuid>aa616b77-41d2-4bb4-9564-c8f6c260992f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'eye-open' and @src = '/images/icons/eye_closed.svg']</value>
      <webElementGuid>60063b3c-8d6f-46bf-b9e8-0c3241f0757a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
