<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_20 Data</name>
   <tag></tag>
   <elementGuidId>62985cdc-370c-428a-9c3d-82aba9f034fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='id_pagination_rowdata_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_pagination_rowdata_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7359b8c8-02b9-4b39-a475-44346710ae48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_pagination_rowdata_1</value>
      <webElementGuid>1f3ac929-142c-4b8d-abad-497911c8cf26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20 Data</value>
      <webElementGuid>a1c479bc-39d0-458d-bdd7-b4885bfab76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_pagination_rowdata_1&quot;)</value>
      <webElementGuid>d28d4273-7a32-4205-b10d-d3b32a704027</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='id_pagination_rowdata_1']</value>
      <webElementGuid>8fc4406c-3a2e-40dc-abf7-fb6a5e7315d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='app']/div/div/main/div[3]/div/div[3]/div/div/div/div/button[2]</value>
      <webElementGuid>7bd33349-3c28-4722-90d8-a7e719954fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sertifikasiku -'])[1]/following::button[3]</value>
      <webElementGuid>ac7c559f-b489-41af-89c4-41f059bc657d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tingkatkan Penjualan dengan Facebook Marketing'])[1]/following::button[3]</value>
      <webElementGuid>5d00197e-1226-427e-9264-c1834567961d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='20']/parent::*</value>
      <webElementGuid>515f3644-d8c3-4b0a-9686-7125ff0bd29f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div/div/div/button[2]</value>
      <webElementGuid>0257abf8-7bf5-4725-8d5c-0055d03621ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'id_pagination_rowdata_1' and (text() = '20 Data' or . = '20 Data')]</value>
      <webElementGuid>aa1dad6e-caa2-4570-ad93-7fe9571a01a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
