<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_search</name>
   <tag></tag>
   <elementGuidId>0e3d537e-ceca-4009-83ab-9e64f4abcf8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='idqtddn9']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.legion-textfield__inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6f490bb0-c106-4d8c-8cdc-5b623d202853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>legion-textfield__inner</value>
      <webElementGuid>e5070203-1a2e-46a7-a12c-537ebfde55a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>5cedb8e2-9dc2-4334-a3e7-a061e8afd3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;md:flex w-full sm:min-w-[1366px]&quot;]/div[@class=&quot;flex-1 transition-all duration-300 ease-in-out md:ml-[285px]&quot;]/main[1]/div[@class=&quot;px-0 md:px-6 py-1 md:pt-1 md:pb-4&quot;]/div[@class=&quot;pt-4 pb-4 md:p-4 border rounded-lg&quot;]/div[@class=&quot;mb-4&quot;]/div[@class=&quot;px-4 pt-6 pb-2&quot;]/div[@id=&quot;idqtddn9&quot;]/span[@class=&quot;legion-textfield__inner&quot;]</value>
      <webElementGuid>b05375f8-ba2f-494b-a8ba-9c0394c2e8bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idqtddn9']/span</value>
      <webElementGuid>ce337deb-b5d9-44ce-8b9d-4253280ea289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kursus yang diminati'])[1]/following::span[1]</value>
      <webElementGuid>506e57e1-5f1e-4609-9fbb-5d24a5bfc035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelatihan Terselesaikan'])[1]/following::span[1]</value>
      <webElementGuid>aca8380f-89c9-4926-a7ce-03963a247fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Kursus'])[1]/preceding::span[5]</value>
      <webElementGuid>ddff6dd2-b0e5-4dea-95aa-18e68ca2f38b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>9c977432-096e-4543-a720-200519bd2cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'search' or . = 'search')]</value>
      <webElementGuid>fcce4287-a38f-46e6-bdca-84a0c7c39aae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
