<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Batalkan Pilihan_legion-image  css-yfh2mk</name>
   <tag></tag>
   <elementGuidId>542f1f0f-adfa-4f79-8fcc-ec94dc28c0d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='id_role_search_hak_akses']/span/span[2]/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>090b605e-a44e-4a7b-b225-a0c000e43c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>legion-image  css-yfh2mk</value>
      <webElementGuid>3dc225e2-e51d-4bc8-a1d5-7299c6160725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>756ab4fd-5679-49ae-bd35-6896d7edc16b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>86ebfbb1-5f57-42e8-be88-7473e16d2d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>50cee513-9c38-4944-a0ee-61ebbb691869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/icons/x.svg</value>
      <webElementGuid>a3636ecc-4652-4bb5-9b56-b8b2d9e92d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ic_search</value>
      <webElementGuid>2e84893b-501d-42fa-9c3a-b3b389ccb707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;md:flex w-full sm:min-w-[1366px]&quot;]/div[@class=&quot;flex-1 transition-all duration-300 ease-in-out md:ml-[285px]&quot;]/main[1]/div[@class=&quot;max-w-screen-2xl mx-auto flex my-4 md:my-10&quot;]/div[2]/form[1]/div[@class=&quot;max-w-full border-t p-4 md:p-8 md:border-2 mt-4 md:rounded-lg&quot;]/div[@class=&quot;flex justify-between flex-wrap items-end mb-4&quot;]/div[@id=&quot;id_role_search_hak_akses&quot;]/span[@class=&quot;legion-textfield__inner&quot;]/span[@class=&quot;legion-textfield__icon&quot;]/button[@class=&quot;h-[13px] w-[13px]&quot;]/img[@class=&quot;legion-image  css-yfh2mk&quot;]</value>
      <webElementGuid>33d88d47-b700-42a8-8a65-2ee4f56ad325</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id_role_search_hak_akses']/span/span[2]/button/img</value>
      <webElementGuid>cf215e57-4190-448c-97f2-de823d03f8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='ic_search'])[2]</value>
      <webElementGuid>061a726f-9205-4eb5-a306-5fdbf7a42ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/button/img</value>
      <webElementGuid>0699e861-e8a6-4c63-b0a7-4175f1bd2ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/icons/x.svg' and @alt = 'ic_search']</value>
      <webElementGuid>5d5d552a-94dc-4488-b6a6-8cee85ae01df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
