<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tidak Aktif</name>
   <tag></tag>
   <elementGuidId>cac8255e-1ba5-4e7a-bc38-d40a4d5915f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='app']/div/div/main/div/div[2]/form/div/div/div[2]/div[2]/label[2]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c40ca4e2-5c63-422d-847e-0f1e8e30c907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style_labelText__8djhY</value>
      <webElementGuid>d60214a9-66e9-455f-b714-c87fc768ac6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tidak Aktif</value>
      <webElementGuid>cdd5c6bb-e13b-495d-9384-6c18453226cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;md:flex w-full sm:min-w-[1366px]&quot;]/div[@class=&quot;flex-1 transition-all duration-300 ease-in-out md:ml-[285px]&quot;]/main[1]/div[@class=&quot;max-w-screen-2xl mx-auto flex my-4 md:my-10&quot;]/div[2]/form[1]/div[@class=&quot;max-w-full border-t p-4 md:p-8 md:border-2 mt-4 md:rounded-lg&quot;]/div[@class=&quot;flex flex-wrap md:flex-nowrap justify-between mb-6 w-full&quot;]/div[@class=&quot;text-sm w-full flex flex-col justify-between&quot;]/div[2]/label[@class=&quot;style_labelContainer__n2Z9_&quot;]/span[@class=&quot;style_labelText__8djhY&quot;]</value>
      <webElementGuid>c88ea2df-8ae9-4baf-a064-f9e50ab32ca0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='app']/div/div/main/div/div[2]/form/div/div/div[2]/div[2]/label[2]/span[2]</value>
      <webElementGuid>dc9df676-fe59-4957-b932-e9237cc35099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktif'])[1]/following::span[2]</value>
      <webElementGuid>1d016dbe-2e68-4424-aa38-357618bf5ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::span[4]</value>
      <webElementGuid>7af23676-10ff-4588-8f36-c82d0a055116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::span[1]</value>
      <webElementGuid>e2a59829-4c27-4037-93a6-31abaa81f92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tidak Aktif']/parent::*</value>
      <webElementGuid>11f97ec1-f33a-491a-9bbd-ab34eb7588d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span[2]</value>
      <webElementGuid>c7639217-9ca5-4909-8664-828f8c672030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tidak Aktif' or . = 'Tidak Aktif')]</value>
      <webElementGuid>41a9550c-af3e-404d-8815-c39f2846aad9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
