<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Batal</name>
   <tag></tag>
   <elementGuidId>4581f8a2-ba3f-4f15-8960-727a147f9dae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='id_pengguna_cancel_status']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_pengguna_cancel_status</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9bd1b679-3448-495c-a33e-e9ef9aabcf23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_pengguna_cancel_status</value>
      <webElementGuid>d1c3798e-bb4c-4f07-a135-811cf9050454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>legion-button legion-button--md legion-button--outline-tertiary  legion-button--center   order-2 md:order-none css-1qci1j0</value>
      <webElementGuid>d185fdcb-0347-4986-949b-be31007cb471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>tertiary</value>
      <webElementGuid>cbd0c715-4942-4e75-b8cb-26b737184424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6b8ed8ea-13cf-4450-b089-42ff6c8c6818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Batal</value>
      <webElementGuid>73c821b8-868b-4deb-a803-e19abbe3c466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_pengguna_cancel_status&quot;)</value>
      <webElementGuid>db5ab575-0ce2-415e-b055-b44fb8b68e5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='id_pengguna_cancel_status']</value>
      <webElementGuid>1d7838f2-0c4c-45ea-aac8-633ca5ae1b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='app']/div/div/main/div[2]/div/div/div/div[3]/button</value>
      <webElementGuid>023951a3-0dbb-4c75-aec0-367261320e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak Aktif'])[4]/following::button[1]</value>
      <webElementGuid>0e13e6be-65f3-487f-b435-575e3fb65ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktif'])[8]/following::button[1]</value>
      <webElementGuid>ecf8100a-7ad3-44ed-9b4f-3519183710aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah Status'])[1]/preceding::button[1]</value>
      <webElementGuid>a5f04464-721b-42a3-bd6a-11370e71d629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>ff610266-3e1f-4459-9fc5-1dea5c3debec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'id_pengguna_cancel_status' and @type = 'button' and (text() = 'Batal' or . = 'Batal')]</value>
      <webElementGuid>f8dd2f62-cd3c-4784-8869-2af44d5dc364</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
