<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>6d13a3ee-28af-478f-b86e-632f487df730</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='field-confirm-password']/span/span/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field-confirm-password > span.legion-textfield__inner > span.legion-textfield__icon > button[type=&quot;button&quot;] > img[alt=&quot;eye-open&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>10035c4e-e32d-4a41-aced-bedd05dee040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>eye-open</value>
      <webElementGuid>63453470-969e-4f92-a42c-ef26064cf47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/icons/eye_closed.svg</value>
      <webElementGuid>b63f485c-40ed-4117-9e68-9ff99b6c637f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>703c25a2-8a04-4381-8bbf-6cd22ae6fc5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;md:flex w-full sm:min-w-[1366px]&quot;]/div[@class=&quot;flex-1 transition-all duration-300 ease-in-out md:ml-[285px]&quot;]/main[1]/div[@class=&quot;flex flex-row my-6 md:my-10&quot;]/div[2]/form[1]/div[@class=&quot;border-[1px] md:border-2 mt-4 p-4 md:p-8 md:rounded-lg&quot;]/div[@class=&quot;mb-6&quot;]/div[@id=&quot;field-confirm-password&quot;]/span[@class=&quot;legion-textfield__inner&quot;]/span[@class=&quot;legion-textfield__icon&quot;]/button[1]/img[1]</value>
      <webElementGuid>82e6fae8-6811-4fd2-b137-e446c59e4141</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-confirm-password']/span/span/button/img</value>
      <webElementGuid>5f8194db-6133-4194-b1be-a579f6285ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='eye-open'])[2]</value>
      <webElementGuid>4221c2e3-852e-41fe-b48f-b7f96ceeee57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/span/span/button/img</value>
      <webElementGuid>70f6b745-6d75-4885-9c98-bb5c7a814552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'eye-open' and @src = '/images/icons/eye_closed.svg']</value>
      <webElementGuid>eaa4b2a4-64c2-4fae-a10f-57c3acd6d3cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
