<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ubah Status</name>
   <tag></tag>
   <elementGuidId>ed46aecf-2a5b-4336-be42-e2ab617692be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='id_role_submit_status']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_role_submit_status</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>feb57be3-52a3-41ce-ab47-10c2c4749e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_role_submit_status</value>
      <webElementGuid>1338cf6e-1948-4f24-a8d0-ceba43caedcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>legion-button legion-button--md legion-button--solid-primary  legion-button--center   order-1 md:order-none css-1i0aso6</value>
      <webElementGuid>6ebc2487-cd95-4e4e-b31b-51d934fb890b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>fe6f832e-b51b-411e-b2a1-5b912deceed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc49fe3c-2c70-404f-879a-9c1f39df7dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ubah Status</value>
      <webElementGuid>8ae4977e-6fe1-47df-964b-a46cdbe559ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_role_submit_status&quot;)</value>
      <webElementGuid>91493e01-d53a-4e60-a9dd-f84a87a988ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='id_role_submit_status']</value>
      <webElementGuid>9407e59b-5484-4b5c-9d3a-3183c8d67a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='app']/div/div/main/div[4]/div/div/div/div[2]/button[2]</value>
      <webElementGuid>733e3ab0-07b5-4ac3-8be6-2796e2fc6d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[3]/following::button[1]</value>
      <webElementGuid>33d32253-329d-4994-ab9a-8509ce13333d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perubahan status akan mempengaruhi hak akses pengguna yang telah terdaftar.'])[1]/following::button[2]</value>
      <webElementGuid>8b190afd-b12c-4c20-961f-90fb2a8f9140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/button[2]</value>
      <webElementGuid>a85fad92-c8c5-4bce-b448-dc0fa6932517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'id_role_submit_status' and @type = 'button' and (text() = 'Ubah Status' or . = 'Ubah Status')]</value>
      <webElementGuid>dd6fb7cf-4176-4a64-b578-f0cc5f69b123</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
