<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ubah Status</name>
   <tag></tag>
   <elementGuidId>b6431f23-b7e6-4a0d-a85f-9a1fc113efe2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='id_pengguna_submit_status']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_pengguna_submit_status</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9c0f920e-a5e0-4aeb-903e-d1d821c1dac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_pengguna_submit_status</value>
      <webElementGuid>a4d74236-6bf1-4a2b-a235-7d367f1ec485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>legion-button legion-button--md legion-button--solid-primary  legion-button--center   order-1 md:order-none css-1i0aso6</value>
      <webElementGuid>1528bd30-a015-4501-9987-632bc160a5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>d43fccdd-9b51-450f-8ba8-2b473c8573b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>40ea1ce8-df41-4952-a745-835b903657d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ubah Status</value>
      <webElementGuid>146b6bbc-d829-44ff-8039-a655c23ed7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_pengguna_submit_status&quot;)</value>
      <webElementGuid>2298dda5-9a23-4068-9d26-c29369181faa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='id_pengguna_submit_status']</value>
      <webElementGuid>547caae5-6679-41d4-865d-62c88ca85580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='app']/div/div/main/div[2]/div/div/div/div[2]/button[2]</value>
      <webElementGuid>620dc865-b059-4b7a-a208-c8d71923b742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/following::button[1]</value>
      <webElementGuid>109b8f7a-b1d1-4390-b16d-d00f2ad04293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perubahan status akan mempengaruhi hak akses pengguna yang telah terdaftar.'])[1]/following::button[2]</value>
      <webElementGuid>86b10acd-1e0f-4f25-9eb7-37fb00b829c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/button[2]</value>
      <webElementGuid>fdfb3470-e23f-48e8-961c-746b3cc43370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'id_pengguna_submit_status' and @type = 'button' and (text() = 'Ubah Status' or . = 'Ubah Status')]</value>
      <webElementGuid>f91a4f89-b444-425e-9289-0b89cff3918b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
