<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pengguna</name>
   <tag></tag>
   <elementGuidId>62a9d678-d99c-4e90-9166-850da634e533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='app']/div/aside/nav/div/ul/li[2]/div/ul/li[2]/span/span/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > span.legion-sidebar__menu > span.legion-sidebar__menu-label > span.legion-sidebar__menu-label-title > a.text-wrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>446b0756-d070-4481-942c-6d5bfc8e8efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-wrap</value>
      <webElementGuid>9f4bcd64-a56d-4ed5-aa62-b7eac3846fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pengguna</value>
      <webElementGuid>8e34a2d6-c49b-47df-a06c-cd1213ba1b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pengguna</value>
      <webElementGuid>dc6c8523-1e29-4d0a-89f7-76a532a231fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;md:flex w-full sm:min-w-[1366px]&quot;]/aside[@class=&quot;transition-all duration-300 ease-in-out expanded border-r h-screen overflow-y-auto fixed left-0 top-0 px-2 bg-primary-900 z-10&quot;]/nav[@class=&quot;mt-5&quot;]/div[@class=&quot;legion-sidebar legion-sidebar--filled css-ejrrch&quot;]/ul[1]/li[@class=&quot;legion-sidebar__has-child&quot;]/div[@class=&quot;legion-sidebar__sub-menu legion-sidebar__sub-menu--active&quot;]/ul[1]/li[2]/span[@class=&quot;legion-sidebar__menu&quot;]/span[@class=&quot;legion-sidebar__menu-label&quot;]/span[@class=&quot;legion-sidebar__menu-label-title&quot;]/a[@class=&quot;text-wrap&quot;]</value>
      <webElementGuid>925f485a-4d2b-474a-b975-612e91b3c317</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='app']/div/aside/nav/div/ul/li[2]/div/ul/li[2]/span/span/span/a</value>
      <webElementGuid>f25cc967-e019-4031-9ee8-e38fccc603b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pengguna')]</value>
      <webElementGuid>4932695b-c8a5-4655-837d-fc9adc3b8e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[1]/following::a[1]</value>
      <webElementGuid>7fb05f3b-33a7-4540-b41f-16d16db823f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akses CMS'])[1]/following::a[2]</value>
      <webElementGuid>d9067124-369b-4248-9b60-f24e9c8afb27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akses Dummy Bypass Prakerja'])[1]/preceding::a[1]</value>
      <webElementGuid>3f772517-8414-4c2c-bc46-7e41786d6b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelola Transaksi'])[1]/preceding::a[2]</value>
      <webElementGuid>fa3abcc9-b57b-4d0a-8505-69ba39000038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pengguna']/parent::*</value>
      <webElementGuid>2f3cf65a-0408-4faf-bae6-9cfe92b29a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/pengguna')]</value>
      <webElementGuid>76508b64-e98f-425e-a204-76cce77e04d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span/span/span/a</value>
      <webElementGuid>8b9e9ef7-2929-4336-8866-b86c97a87e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/pengguna' and (text() = 'Pengguna' or . = 'Pengguna')]</value>
      <webElementGuid>9eff41f9-fb30-464c-a034-8751098173c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
