<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Role</name>
   <tag></tag>
   <elementGuidId>76b3fd93-1bb6-48e5-b9e8-68bd21435f45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='app']/div/aside/nav/div/ul/li[2]/div/ul/li/span/span/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.legion-sidebar__sub-menu.legion-sidebar__sub-menu--active > ul > li > span.legion-sidebar__menu > span.legion-sidebar__menu-label > span.legion-sidebar__menu-label-title > a.text-wrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>96b211eb-6dc3-415c-9265-f8b2892509b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-wrap</value>
      <webElementGuid>6201ec46-cf01-4ba3-8306-4145ee01f8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/role</value>
      <webElementGuid>982d0ed6-c9ee-4d31-8126-bd2eaace7a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Role</value>
      <webElementGuid>bbfa44da-2f2b-4348-a1a6-816a29739e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;md:flex w-full sm:min-w-[1366px]&quot;]/aside[@class=&quot;transition-all duration-300 ease-in-out expanded border-r h-screen overflow-y-auto fixed left-0 top-0 px-2 bg-primary-900 z-10&quot;]/nav[@class=&quot;mt-5&quot;]/div[@class=&quot;legion-sidebar legion-sidebar--filled css-ejrrch&quot;]/ul[1]/li[@class=&quot;legion-sidebar__has-child&quot;]/div[@class=&quot;legion-sidebar__sub-menu legion-sidebar__sub-menu--active&quot;]/ul[1]/li[1]/span[@class=&quot;legion-sidebar__menu&quot;]/span[@class=&quot;legion-sidebar__menu-label&quot;]/span[@class=&quot;legion-sidebar__menu-label-title&quot;]/a[@class=&quot;text-wrap&quot;]</value>
      <webElementGuid>77aed48b-c34e-41b3-bb7a-473a6a7c3013</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='app']/div/aside/nav/div/ul/li[2]/div/ul/li/span/span/span/a</value>
      <webElementGuid>8a3495e3-eb89-44eb-a86b-7a886d9f6813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Role')]</value>
      <webElementGuid>8c13118b-7b59-4db9-8dd4-143595f10b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akses CMS'])[1]/following::a[1]</value>
      <webElementGuid>2e326aa5-70fa-465f-9654-b59b945bfe19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/following::a[1]</value>
      <webElementGuid>1686f6cb-2b16-402c-987b-4e6310d0d286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengguna'])[1]/preceding::a[1]</value>
      <webElementGuid>31ab0d2d-8764-4d88-bbaf-83b38d28ad6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akses Dummy Bypass Prakerja'])[1]/preceding::a[2]</value>
      <webElementGuid>1e720436-77c6-4227-a458-c579e3e42c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Role']/parent::*</value>
      <webElementGuid>f045df0e-ae54-4880-9e4c-e21b1d2c3b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/role')]</value>
      <webElementGuid>f20a81d3-dac9-4b4d-84ef-67da2894eda0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li/span/span/span/a</value>
      <webElementGuid>6e5d3f98-cf4e-43c1-8cdd-d3c664e424a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/role' and (text() = 'Role' or . = 'Role')]</value>
      <webElementGuid>d5b07eee-d3c9-4eac-9d9b-cafcaa50084b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
