<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Role</name>
   <tag></tag>
   <elementGuidId>88c8a259-f792-4763-ad47-43d60414e57b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='id_role_add']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_role_add</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e2edadcd-ad8d-428d-a66e-02330bc7c634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_role_add</value>
      <webElementGuid>b2521548-4666-4c63-aeba-dcef775c1713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>legion-button legion-button--md legion-button--solid-primary css-1i0aso6</value>
      <webElementGuid>3fa783a1-d0cc-45b2-8d3f-0f765b9210c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>8068adc3-408e-4bea-b5e7-e0e84a79ba87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>41891ce9-2179-4ee9-9623-4cbc95bf7ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Role</value>
      <webElementGuid>10ccf4fd-7d13-41b7-851a-3d18d314750f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_role_add&quot;)</value>
      <webElementGuid>575f8b02-5055-42a0-9b3f-b4867e3a74ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='id_role_add']</value>
      <webElementGuid>402324e7-cf46-4e61-8ffc-23ed42942e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='app']/div/div/main/div/div/button</value>
      <webElementGuid>c0a8c013-4fb5-4684-8dba-34ffea837bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[2]/following::button[1]</value>
      <webElementGuid>0f69c341-5dd0-499a-bc0b-27fec6384c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='superadmin'])[1]/following::button[1]</value>
      <webElementGuid>254014b3-e019-4d42-9b42-ca90b2898b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[4]/preceding::button[1]</value>
      <webElementGuid>2544ff8c-d9d9-42c3-9b61-92dd2da952ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/button</value>
      <webElementGuid>3b3488bd-4d08-4f86-80f1-8a132dc85ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'id_role_add' and @type = 'button' and (text() = 'Role' or . = 'Role')]</value>
      <webElementGuid>e7f4c03f-bed7-4241-89b8-4ba460d53386</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
