<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_20 Data</name>
   <tag></tag>
   <elementGuidId>a5ed23d5-3e27-466c-9f24-1c15c32f4089</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='id_pagination_rowdata_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_pagination_rowdata_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>617219b0-3562-4e0c-8424-364a3224b93d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_pagination_rowdata_1</value>
      <webElementGuid>637a8316-2c01-49a4-a96f-c0667ae4e9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20 Data</value>
      <webElementGuid>ab3170bf-f876-4a51-8ad8-9135e27d5594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_pagination_rowdata_1&quot;)</value>
      <webElementGuid>78d13dd9-af4d-450b-99b1-ba889561a3e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='id_pagination_rowdata_1']</value>
      <webElementGuid>ce12729b-0010-4c50-bf3e-f0ec56a9f5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='app']/div/div/main/div/div[2]/div[3]/div/div/div/div/button[2]</value>
      <webElementGuid>f363b0ba-ee8c-429e-82eb-7ab43f060a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktif'])[9]/following::button[3]</value>
      <webElementGuid>517bd1f3-6be0-46b3-b650-727693b2dd98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah Status Role null?'])[1]/preceding::button[6]</value>
      <webElementGuid>0c98cd7c-8065-4a6c-87cc-def5c2a0a939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='20']/parent::*</value>
      <webElementGuid>618f896b-d30e-4281-9640-2a875e808604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div/div/button[2]</value>
      <webElementGuid>bb162916-5df2-4b2f-837c-135728849101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'id_pagination_rowdata_1' and (text() = '20 Data' or . = '20 Data')]</value>
      <webElementGuid>d936fdb2-98c1-4332-9560-5c54a2fcc9fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
