<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ubah Data</name>
   <tag></tag>
   <elementGuidId>b68545a4-ce63-4e3a-9032-e93e003af5fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='id_role_ubah_data']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_role_ubah_data</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dc031806-59f1-49f2-a961-db5ffebfb6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer p-2 hover:bg-[#F0FBFF]  rounded-md text-xs mb-1</value>
      <webElementGuid>9e292df9-f33e-4f23-aa56-e229cb0b5607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>button-edit-data</value>
      <webElementGuid>35dac872-8518-477a-93f4-8ee294c953ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_role_ubah_data</value>
      <webElementGuid>ad02c075-6c57-4ae7-b151-71eb6d1df557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ubah Data</value>
      <webElementGuid>709f4539-1876-41a8-9c59-5766c7b54467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_role_ubah_data&quot;)</value>
      <webElementGuid>04a222bc-6a71-4bc0-9307-56aaca613a4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='id_role_ubah_data']</value>
      <webElementGuid>c33ef9ea-4c66-428d-9a54-989eba89d8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='app']/div[2]/div</value>
      <webElementGuid>b8ef2c9c-ead7-4328-b05f-42015a872af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[2]</value>
      <webElementGuid>3a040f14-96c9-4d68-8a47-ba2419002fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah Status'])[3]/preceding::div[1]</value>
      <webElementGuid>5643f119-82e5-4e33-abe3-54180c80c042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Data'])[1]/preceding::div[2]</value>
      <webElementGuid>5118cf3e-6553-4c10-8084-8412316ae083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ubah Data']/parent::*</value>
      <webElementGuid>759fabde-8652-4bf6-8ac8-5284a2582625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>17c1213d-b4bc-4f61-8ba4-96f01c293362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'id_role_ubah_data' and (text() = 'Ubah Data' or . = 'Ubah Data')]</value>
      <webElementGuid>4ecd2c51-6f37-44a2-bcc1-47cca91d23a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
