<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hapus Data</name>
   <tag></tag>
   <elementGuidId>fba0abcc-c661-44a6-8326-e3fc290b49b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='id_role_delete_data']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_role_delete_data</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>13ee45de-e27a-4e10-8e6c-4aa2543c4045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer p-2 hover:bg-[#F0FBFF] rounded-md text-xs</value>
      <webElementGuid>9a321d0a-c2d9-4a45-bdb5-263c74da9e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>button-delete-data</value>
      <webElementGuid>94c9eb45-47ac-4b5c-bfe4-21f7f733abb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_role_delete_data</value>
      <webElementGuid>17b4f01e-b06c-4633-a199-9b716522560f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hapus Data</value>
      <webElementGuid>34eeec90-22d1-4355-a5fc-8bfd0303d51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_role_delete_data&quot;)</value>
      <webElementGuid>4f634b36-990f-445c-b177-e2aa3c7e5eee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='id_role_delete_data']</value>
      <webElementGuid>3df5886b-4d14-4ea3-a35c-87bf1cc142cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='app']/div[2]/div[3]</value>
      <webElementGuid>80de54c6-f009-4eb0-ac32-5b787216762a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah Status'])[3]/following::div[1]</value>
      <webElementGuid>ef156b48-c8c6-4fb3-abe8-0194f011d6c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah Data'])[1]/following::div[2]</value>
      <webElementGuid>e7f9f890-f78e-4c50-a792-c94202c39fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hapus Data']/parent::*</value>
      <webElementGuid>f6fbfb17-608e-4c8b-9ff1-dc79c0618275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]</value>
      <webElementGuid>6bfb1f75-f388-4c22-802c-d0d9baf546ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'id_role_delete_data' and (text() = 'Hapus Data' or . = 'Hapus Data')]</value>
      <webElementGuid>47a75ad6-5abc-4246-8b33-7f7328201b88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
