<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ubah Status</name>
   <tag></tag>
   <elementGuidId>9580d537-c3a1-4673-b281-08130c58a2ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='id_role_ubah_status']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_role_ubah_status</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e3d0ecde-0b36-4dfb-9e9d-180726f685d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer p-2 hover:bg-[#F0FBFF] rounded-md text-xs mb-1</value>
      <webElementGuid>0af63894-42f8-402c-8d94-7a7a4153b762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>button-edit-status</value>
      <webElementGuid>553c92f2-335c-4eaf-9b0a-b8d45bb6cea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_role_ubah_status</value>
      <webElementGuid>8b773252-0d6d-413f-b9ee-dc6293b3d30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ubah Status</value>
      <webElementGuid>60cfef14-7d9e-4a2a-bb03-a6a152b2aefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_role_ubah_status&quot;)</value>
      <webElementGuid>9dbe19f2-1bc6-45e4-816a-92a5c271679f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='id_role_ubah_status']</value>
      <webElementGuid>9be1b4f6-6f42-4ff8-8bd1-fb2676f52521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='app']/div[2]/div[2]</value>
      <webElementGuid>0bc67303-c6ca-4708-bb04-1cab7d29f9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah Data'])[1]/following::div[1]</value>
      <webElementGuid>72698485-8aba-4893-8618-a5ba68b40e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Data'])[1]/preceding::div[1]</value>
      <webElementGuid>d2a665e2-4af8-40ca-84da-9426776343fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>5bd8d288-210a-43bb-8b3a-85953e1dd897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'id_role_ubah_status' and (text() = 'Ubah Status' or . = 'Ubah Status')]</value>
      <webElementGuid>d7eaf7cf-9461-4a9d-8f92-8d99b9f6dd15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
