<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>df52acb8-fe6f-4afb-a7ce-2c62b6fc8c1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='app']/div/div/main/div/div[2]/div[2]/div/table/tbody/tr/td[4]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;ic&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a4f33976-d609-4ef6-8add-8593f3b18a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ic</value>
      <webElementGuid>77c9ccda-a4b1-4496-9f0f-ace3828e9be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/icons/dots-vertical.svg</value>
      <webElementGuid>4b57417d-8640-4c3b-9bdd-0257f8cc599e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;md:flex w-full sm:min-w-[1366px]&quot;]/div[@class=&quot;flex-1 transition-all duration-300 ease-in-out md:ml-[285px]&quot;]/main[1]/div[@class=&quot;p-6&quot;]/div[@class=&quot;pt-4 pb-4 md:p-4 border rounded-lg&quot;]/div[@class=&quot;overflow-auto&quot;]/div[@class=&quot;css-pe7vlx&quot;]/table[@class=&quot;legion-table   table-auto&quot;]/tbody[1]/tr[1]/td[@class=&quot;sticky sticky-shadow bg-white sticky-shadow-right&quot;]/div[@class=&quot;css-iolj2p&quot;]/div[@class=&quot;pointer h-[16px] w-[16px] m-auto&quot;]/img[1]</value>
      <webElementGuid>939ee8a2-856f-487a-8a9e-4eef9d07dfc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='app']/div/div/main/div/div[2]/div[2]/div/table/tbody/tr/td[4]/div/div/img</value>
      <webElementGuid>75e5ea00-74b5-4e47-8e55-9fb1e793479e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='ic']</value>
      <webElementGuid>036b5915-df38-4cd4-b926-180957dc65d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/img</value>
      <webElementGuid>5c97797f-9496-4147-a642-d7af3ad69afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'ic' and @src = '/images/icons/dots-vertical.svg']</value>
      <webElementGuid>f25393d8-3324-45f6-aeb5-70d40cca534c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
