<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Role_legion-image  css-yfh2mk</name>
   <tag></tag>
   <elementGuidId>3f0121a4-3564-4375-bdc6-9c86391145de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='id_role_search']/span/span[2]/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button > img.legion-image.css-yfh2mk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>086f7e12-ec62-46ab-a57f-900eeca144f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>legion-image  css-yfh2mk</value>
      <webElementGuid>7280ffe2-9848-478a-a3af-a04ea16da028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>abf6c32d-4e61-4503-b68e-fa901ffeec2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>5fb2050c-5865-4c4a-9ffc-d07c9773aea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>6b489bbe-987b-4346-88fa-4c4cf1f4d1af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/icons/x.svg</value>
      <webElementGuid>a8244e83-a698-41c1-acf8-7707d750a285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ic_search</value>
      <webElementGuid>00f9f770-fa33-438e-9f47-ff50c7dfddcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;md:flex w-full sm:min-w-[1366px]&quot;]/div[@class=&quot;flex-1 transition-all duration-300 ease-in-out md:ml-[285px]&quot;]/main[1]/div[@class=&quot;p-6&quot;]/div[@class=&quot;pt-4 pb-4 md:p-4 border rounded-lg&quot;]/div[@class=&quot;mb-4&quot;]/div[@class=&quot;flex justify-between&quot;]/div[@class=&quot;flex-1 flex px-4 md:px-0 gap-x-4&quot;]/div[@id=&quot;id_role_search&quot;]/span[@class=&quot;legion-textfield__inner&quot;]/span[@class=&quot;legion-textfield__icon&quot;]/button[1]/img[@class=&quot;legion-image  css-yfh2mk&quot;]</value>
      <webElementGuid>113a3ad0-ac98-4a38-8ae0-96c6b6118079</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id_role_search']/span/span[2]/button/img</value>
      <webElementGuid>5bdee1fe-d25b-468a-a949-0ad0f7f0e942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='ic_search'])[2]</value>
      <webElementGuid>35c5b558-b966-4471-9d13-09ce7a1c49e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/button/img</value>
      <webElementGuid>e02c9f3a-4206-45d0-8402-6eb489f39d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/icons/x.svg' and @alt = 'ic_search']</value>
      <webElementGuid>7e316d28-a2cb-4266-9cdf-0e70dd73c0f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
