<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_20 Data</name>
   <tag></tag>
   <elementGuidId>c460c12a-a1b9-4fe9-ad24-b7552c42fd24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='id_pagination_rowdata_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_pagination_rowdata_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>90535fab-71aa-4cde-9282-abb5251214ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_pagination_rowdata_1</value>
      <webElementGuid>ca023a22-d8f9-4222-9d9a-6d254434eb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20 Data</value>
      <webElementGuid>760fdb11-fef9-4063-97ee-299198bda55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_pagination_rowdata_1&quot;)</value>
      <webElementGuid>aa4197b1-72ee-472c-b79c-7d1b89f3773f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='id_pagination_rowdata_1']</value>
      <webElementGuid>7372a7a3-4ff9-4036-b5ff-987c45eef619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='app']/div/div/main/div/div[2]/div[3]/div/div/div/div/button[2]</value>
      <webElementGuid>9d37e094-2f27-4418-bda5-0882e9ae5ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktif'])[7]/following::button[3]</value>
      <webElementGuid>3a7efcdf-8148-48c5-8dd0-2ad408d307bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin partner'])[2]/following::button[3]</value>
      <webElementGuid>06986610-66bb-4054-a149-3ab0c7ea0f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='20']/parent::*</value>
      <webElementGuid>469aac53-1ac6-42ca-b768-b5c9309f13b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/button[2]</value>
      <webElementGuid>1e85978a-f09d-4b3f-9644-71e98073e6ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'id_pagination_rowdata_1' and (text() = '20 Data' or . = '20 Data')]</value>
      <webElementGuid>9e1dce0a-d0d0-4685-a4ba-27148d3c1bd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
