<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_50 Data</name>
   <tag></tag>
   <elementGuidId>7680913f-d31e-4dc9-b1fe-4fbe8171b4e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='id_pagination_rowdata_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_pagination_rowdata_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8afbd1cf-6f23-428b-ae33-0e63eba37600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_pagination_rowdata_2</value>
      <webElementGuid>182c1e2b-eca0-40da-b762-d92dd0badbf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>50 Data</value>
      <webElementGuid>b430e019-bbe9-4411-80b6-5f8fb79656b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_pagination_rowdata_2&quot;)</value>
      <webElementGuid>8a6008a6-6332-4bd3-961d-f7f85f70013e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='id_pagination_rowdata_2']</value>
      <webElementGuid>1a0d8be0-af6d-4da8-b65e-6f629c02a109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='app']/div/div/main/div/div[2]/div[3]/div/div/div/div/button[3]</value>
      <webElementGuid>6610a40c-5403-4b29-a052-6825e0e5419c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktif'])[7]/following::button[4]</value>
      <webElementGuid>ffd510eb-9d91-453d-b90c-fd9d4ac4e994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin partner'])[2]/following::button[4]</value>
      <webElementGuid>f6a37792-1347-4848-9f4b-181d206da422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='50']/parent::*</value>
      <webElementGuid>924d2305-7069-4c63-a3dd-dbd997cd7138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>0a904991-80c7-45be-a387-439bb33a1dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'id_pagination_rowdata_2' and (text() = '50 Data' or . = '50 Data')]</value>
      <webElementGuid>b8398dcf-ea75-41cd-b8a9-b68ba143238e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
