<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ubah Status</name>
   <tag></tag>
   <elementGuidId>6569bea6-8c10-4a9e-8277-abdc420de53c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='app']/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>95cdbe65-b0cb-486f-8c7d-0b020a132cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer p-2 hover:bg-[#F0FBFF] rounded-md text-xs mb-1</value>
      <webElementGuid>727090db-e294-4c13-a287-473e56a065e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>button-edit-status</value>
      <webElementGuid>8f531fc9-88b5-43d8-8b02-03626bad0bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ubah Status</value>
      <webElementGuid>dcf40ef8-c6fc-4d74-859b-6a9819cf4bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;css-c3jlvn&quot;]/div[@class=&quot;cursor-pointer p-2 hover:bg-[#F0FBFF] rounded-md text-xs mb-1&quot;]</value>
      <webElementGuid>b3d904cc-19cb-4fc3-9abe-e18bf8434d10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='app']/div[2]/div[2]</value>
      <webElementGuid>587abfd5-33f9-4ac1-8542-28b3feb8a495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah Data'])[1]/following::div[1]</value>
      <webElementGuid>238a618a-e24b-41e4-a9a3-8961f63ff060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[3]</value>
      <webElementGuid>a43d7ed9-0002-436f-a10c-be60d2a78c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Data'])[1]/preceding::div[1]</value>
      <webElementGuid>5c3f7fa0-db07-4837-9ee4-bbe18386ad15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ubah Status']/parent::*</value>
      <webElementGuid>d94d4910-6083-4f2b-a09f-77382caf567c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>11d0e5eb-9cb7-418e-aebb-43bc6c637d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ubah Status' or . = 'Ubah Status')]</value>
      <webElementGuid>5747e5d3-eacf-4dae-a77a-7e54db402105</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
