<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>b773fa4f-9e21-432d-8299-b739d456d5b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='app']/div/div/main/div/div[2]/div[2]/div/table/tbody/tr/td[5]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;ic&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a120dd23-748e-4092-a286-0793b2a7cc44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ic</value>
      <webElementGuid>b2b1c90d-af81-449d-a4f5-8e08396792f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/icons/dots-vertical.svg</value>
      <webElementGuid>277e92b6-2cf3-48cd-b01f-de1de77c6d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;md:flex w-full sm:min-w-[1366px]&quot;]/div[@class=&quot;flex-1 transition-all duration-300 ease-in-out md:ml-[285px]&quot;]/main[1]/div[@class=&quot;p-6&quot;]/div[@class=&quot;pt-4 pb-4 md:p-4 border rounded-lg&quot;]/div[@class=&quot;overflow-auto&quot;]/div[@class=&quot;css-pe7vlx&quot;]/table[@class=&quot;legion-table   table-auto&quot;]/tbody[1]/tr[1]/td[@class=&quot;sticky sticky-shadow bg-white sticky-shadow-right&quot;]/div[@class=&quot;css-iolj2p&quot;]/div[@class=&quot;pointer h-[16px] w-[16px] m-auto&quot;]/img[1]</value>
      <webElementGuid>6829c1c6-bc95-4a86-9061-94b0e6260e0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='app']/div/div/main/div/div[2]/div[2]/div/table/tbody/tr/td[5]/div/div/img</value>
      <webElementGuid>6ebd9c38-8ea7-49fe-8eeb-027705158769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='ic']</value>
      <webElementGuid>fcad1e70-c062-4d77-9480-cbcbd09d189a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/img</value>
      <webElementGuid>aa4e3af3-8331-4cde-a199-01172c085f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'ic' and @src = '/images/icons/dots-vertical.svg']</value>
      <webElementGuid>8841dc46-d77f-4f61-95e7-72a17d8ac0d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
