<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Pengguna_legion-image  css-yfh2mk</name>
   <tag></tag>
   <elementGuidId>7ede4e8b-835b-4e9f-b53e-ec35fb1eefde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='id_pengguna_search']/span/span[2]/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button > img.legion-image.css-yfh2mk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>251b1265-c544-4487-8382-a2e43702d9f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>legion-image  css-yfh2mk</value>
      <webElementGuid>9ea035bd-f9e3-4487-a5d6-8b49dfa62ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>938b5ebd-663d-4f5a-9d5f-21edb2da5508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>d5ad39cb-5e24-4138-a16a-3dfa84da2fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>98d9957c-db1c-4ddf-b864-9559f078f538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/icons/x.svg</value>
      <webElementGuid>cc42803c-62a8-4a27-ba67-35c0f544b1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ic_search</value>
      <webElementGuid>ad78169a-d6b9-4b48-8644-99cc6f77cc6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;md:flex w-full sm:min-w-[1366px]&quot;]/div[@class=&quot;flex-1 transition-all duration-300 ease-in-out md:ml-[285px]&quot;]/main[1]/div[@class=&quot;p-6&quot;]/div[@class=&quot;pt-4 pb-4 md:p-4 border rounded-lg&quot;]/div[@class=&quot;mb-4&quot;]/div[@class=&quot;flex justify-between&quot;]/div[@class=&quot;flex-1 flex gap-2 md:gap-4 flex-wrap px-2&quot;]/div[@id=&quot;id_pengguna_search&quot;]/span[@class=&quot;legion-textfield__inner&quot;]/span[@class=&quot;legion-textfield__icon&quot;]/button[1]/img[@class=&quot;legion-image  css-yfh2mk&quot;]</value>
      <webElementGuid>a5c1fd20-437f-4355-879d-acf26ad517ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id_pengguna_search']/span/span[2]/button/img</value>
      <webElementGuid>3ab942aa-a653-479f-8e4e-5dc20744c556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='ic_search'])[2]</value>
      <webElementGuid>29b1464d-8656-4ff8-a42a-dda3dabe6b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/button/img</value>
      <webElementGuid>3930d99f-471f-4caf-b1da-1f365c9ec924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/icons/x.svg' and @alt = 'ic_search']</value>
      <webElementGuid>30cab00f-fa79-47c6-bc90-71abffdb380f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
